### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by XamarinDeveloper** [ilyalatt/Telega#23]
Hey, I wanted to create some programs with a C# lib for TG and it's the best one I've found so far, but I wanna know if you're gonna continue updating it or it's dead :thinking:
'cause there has been some update on tdlib and there is no sign of them here

**Comment by ilyalatt** [comment]
Hi. Thank you for interest! The project is not dead. There are features in Issues that I do not want to implement because it seems nobody needs them for now. There are some bugs that I know but do not fix them because these are not critical for my project that uses this library. I try to close issues from other people as soon as I can. I helped some people in a private chat. The problem is that count of users of this library is really small. So I do not want to put work into the project when I know that this work will not help anyone. I have tried to recommend the library to users of TLSharp a few times. It seems like patterns that are used in Telega are obstacle for many people. I mean patterns like `Option` type, discriminated unions. Do you have ideas of how to bring people to the project despite this things?

**Comment by XamarinDeveloper** [comment]
not actually :( I myself came here because it's using layer 104 tg scheme when the most updated one out there, is using layer 88 😐
I do not care about patterns used in the library as long as it does what I need, and actually I think these are pretty cool :D
I sat there and read all of the wiki, it was so attractive for me :)
but I dunno why people are being close-minded programming world is world of changes if you can't conform to these changes I think you are no programmer at all!

I hope that there would be more attention to this project :)

and sorry for not helping at all 😅

**Comment by ilyalatt** [comment]
Oh, I am pleased.
Maybe I will find time to make a post for a tech site like medium.com to bring more attention to the project.
If you have any issues feel free to submit them :)
