### ISSUE TITLE
Mark dialog as read not working

### ISSUE THREAD

**Issue by derodevil** [ilyalatt/Telega#79]
```
  var recipient = new InputPeer.UserTag(user.Default.Id, user.Default.AccessHash.Value);
  var peer = new InputDialogPeer.DefaultTag(recipient);
  await tg.Call(new Telega.Rpc.Dto.Functions.Messages.MarkDialogUnread(false, peer)); 
```
I called the above codes on `Subscribe`. I want the incoming message will automatically be marked as read

**Comment by ilyalatt** [comment]
I guess this function is intended for the opposing action. Try `ReadDiscussion`. You can browse available API methods directly from the scheme [here](https://github.com/telegramdesktop/tdesktop/blob/96c86b3e49c600256c3a7b1f3c88750931f7d1b9/Telegram/Resources/tl/api.tl#L1434).

**Comment by derodevil** [comment]
Setting up the `unread` parameter to true and false resulted nothing

**Comment by ilyalatt** [comment]
That means that your assumptions about this method are wrong. It can be a method reserved for a future use for example. I am not sure what it is for because you can not just 'unread' discussion. You need to have some set of messages to mark them as unreaded and it is not clear what is this set (maybe messages with lifetime less than some threshold). Anyway, you need to use `ReadDiscussion`, not `MarkDialogUnread`.
